/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jFrame;

import java.awt.BorderLayout;
import java.awt.Color;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author IJAMY
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
        showPieChart();
    }
    public void showPieChart(){
        
        //create dataset
      DefaultPieDataset barDataset = new DefaultPieDataset( );
      barDataset.setValue("Geography" , Double.valueOf(20));  
      barDataset.setValue("Physics" , Double.valueOf(20));   
      barDataset.setValue("Maths for SCience" , Double.valueOf(40));    
      barDataset.setValue("Chemistry" , Double.valueOf(10));  
      
      //create chart
       JFreeChart piechart = ChartFactory.createPieChart("Borrowed Books ",barDataset, false,true,false);//explain
      
        PiePlot piePlot =(PiePlot) piechart.getPlot();
      
       //changing pie chart blocks colors
       piePlot.setSectionPaint("Geography", new Color(255,255,102));
        piePlot.setSectionPaint("Physics", new Color(102,255,102));
        piePlot.setSectionPaint("Maths for SCience", new Color(255,102,153));
        piePlot.setSectionPaint("Chemistry", new Color(0,204,204));
      
       
        piePlot.setBackgroundPaint(Color.white);
        
        //create chartPanel to display chart(graph)
        ChartPanel barChartPanel = new ChartPanel(piechart);
        pieChartPanel.removeAll();
        pieChartPanel.add(barChartPanel, BorderLayout.CENTER);
        pieChartPanel.validate();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        menu = new javax.swing.JPanel();
        homepage = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        dashboard = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        jPanel34 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel32 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel33 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel28 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        main_component = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        books_count = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        jLabel51 = new javax.swing.JLabel();
        jPanel27 = new javax.swing.JPanel();
        jLabel52 = new javax.swing.JLabel();
        jPanel29 = new javax.swing.JPanel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jPanel30 = new javax.swing.JPanel();
        jLabel55 = new javax.swing.JLabel();
        jPanel31 = new javax.swing.JPanel();
        jLabel56 = new javax.swing.JLabel();
        jPanel35 = new javax.swing.JPanel();
        jLabel57 = new javax.swing.JLabel();
        jPanel36 = new javax.swing.JPanel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jPanel37 = new javax.swing.JPanel();
        jLabel63 = new javax.swing.JLabel();
        jPanel38 = new javax.swing.JPanel();
        jLabel64 = new javax.swing.JLabel();
        jPanel39 = new javax.swing.JPanel();
        jLabel65 = new javax.swing.JLabel();
        jPanel40 = new javax.swing.JPanel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jPanel41 = new javax.swing.JPanel();
        jLabel68 = new javax.swing.JLabel();
        jPanel42 = new javax.swing.JPanel();
        jLabel69 = new javax.swing.JLabel();
        jPanel43 = new javax.swing.JPanel();
        jLabel70 = new javax.swing.JLabel();
        jPanel44 = new javax.swing.JPanel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jPanel45 = new javax.swing.JPanel();
        jLabel81 = new javax.swing.JLabel();
        jPanel46 = new javax.swing.JPanel();
        jLabel82 = new javax.swing.JLabel();
        jPanel47 = new javax.swing.JPanel();
        jLabel83 = new javax.swing.JLabel();
        jPanel48 = new javax.swing.JPanel();
        jLabel84 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jPanel49 = new javax.swing.JPanel();
        jLabel86 = new javax.swing.JLabel();
        jPanel50 = new javax.swing.JPanel();
        jLabel87 = new javax.swing.JLabel();
        jPanel51 = new javax.swing.JPanel();
        jLabel88 = new javax.swing.JLabel();
        jPanel52 = new javax.swing.JPanel();
        jLabel89 = new javax.swing.JLabel();
        jLabel90 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        jLabel92 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        jPanel53 = new javax.swing.JPanel();
        jLabel94 = new javax.swing.JLabel();
        jPanel54 = new javax.swing.JPanel();
        jLabel95 = new javax.swing.JLabel();
        jPanel55 = new javax.swing.JPanel();
        jLabel96 = new javax.swing.JLabel();
        jPanel56 = new javax.swing.JPanel();
        jLabel97 = new javax.swing.JLabel();
        jLabel98 = new javax.swing.JLabel();
        jPanel57 = new javax.swing.JPanel();
        jLabel99 = new javax.swing.JLabel();
        jPanel58 = new javax.swing.JPanel();
        jLabel100 = new javax.swing.JLabel();
        jPanel59 = new javax.swing.JPanel();
        jLabel101 = new javax.swing.JLabel();
        jPanel60 = new javax.swing.JPanel();
        jLabel102 = new javax.swing.JLabel();
        jLabel103 = new javax.swing.JLabel();
        jLabel104 = new javax.swing.JLabel();
        jLabel105 = new javax.swing.JLabel();
        jLabel106 = new javax.swing.JLabel();
        jLabel107 = new javax.swing.JLabel();
        jLabel108 = new javax.swing.JLabel();
        jLabel109 = new javax.swing.JLabel();
        jLabel110 = new javax.swing.JLabel();
        jLabel111 = new javax.swing.JLabel();
        students_count = new javax.swing.JLabel();
        defaulters = new javax.swing.JLabel();
        jPanel61 = new javax.swing.JPanel();
        jLabel112 = new javax.swing.JLabel();
        jPanel62 = new javax.swing.JPanel();
        jLabel113 = new javax.swing.JLabel();
        jPanel63 = new javax.swing.JPanel();
        jLabel114 = new javax.swing.JLabel();
        jPanel64 = new javax.swing.JPanel();
        jLabel115 = new javax.swing.JLabel();
        jLabel116 = new javax.swing.JLabel();
        jPanel65 = new javax.swing.JPanel();
        jLabel117 = new javax.swing.JLabel();
        jPanel66 = new javax.swing.JPanel();
        jLabel118 = new javax.swing.JLabel();
        jPanel67 = new javax.swing.JPanel();
        jLabel119 = new javax.swing.JLabel();
        jPanel68 = new javax.swing.JPanel();
        jLabel120 = new javax.swing.JLabel();
        jLabel121 = new javax.swing.JLabel();
        jLabel122 = new javax.swing.JLabel();
        jLabel123 = new javax.swing.JLabel();
        jLabel124 = new javax.swing.JLabel();
        jPanel69 = new javax.swing.JPanel();
        jLabel125 = new javax.swing.JLabel();
        jPanel70 = new javax.swing.JPanel();
        jLabel126 = new javax.swing.JLabel();
        jPanel71 = new javax.swing.JPanel();
        jLabel127 = new javax.swing.JLabel();
        jPanel72 = new javax.swing.JPanel();
        jLabel128 = new javax.swing.JLabel();
        jLabel129 = new javax.swing.JLabel();
        jPanel73 = new javax.swing.JPanel();
        jLabel130 = new javax.swing.JLabel();
        jPanel74 = new javax.swing.JPanel();
        jLabel131 = new javax.swing.JLabel();
        jPanel75 = new javax.swing.JPanel();
        jLabel132 = new javax.swing.JLabel();
        jPanel76 = new javax.swing.JPanel();
        jLabel133 = new javax.swing.JLabel();
        jLabel134 = new javax.swing.JLabel();
        jLabel135 = new javax.swing.JLabel();
        jLabel136 = new javax.swing.JLabel();
        jLabel137 = new javax.swing.JLabel();
        jLabel138 = new javax.swing.JLabel();
        jLabel139 = new javax.swing.JLabel();
        jLabel140 = new javax.swing.JLabel();
        jLabel141 = new javax.swing.JLabel();
        jLabel142 = new javax.swing.JLabel();
        IssuedBooks = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        rSTableMetro1 = new rojeru_san.complementos.RSTableMetro();
        books_count1 = new javax.swing.JLabel();
        books_count2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        rSTableMetro2 = new rojeru_san.complementos.RSTableMetro();
        pieChartPanel = new javax.swing.JPanel();

        jPanel3.setBackground(new java.awt.Color(0, 102, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 204, 204)));
        jPanel3.setFont(new java.awt.Font("Rockwell Nova Extra Bold", 1, 18)); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 255));
        jLabel11.setText("ACTIONS");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(108, 99, 255));
        header.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 204, 204)));
        header.setFont(new java.awt.Font("Rockwell Nova Extra Bold", 1, 18)); // NOI18N
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_menu_48px_1.png"))); // NOI18N
        header.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel2.setBackground(new java.awt.Color(50, 50, 50));
        header.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 5, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("LIBRARY MANAGEMENT SYSTEM");
        header.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 6, 280, 60));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("X");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        header.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1520, 10, 60, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/male_user_50px.png"))); // NOI18N
        jLabel4.setText("WELCOME,ADMIN");
        header.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 10, 240, -1));

        getContentPane().add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1700, 70));

        menu.setBackground(new java.awt.Color(51, 51, 51));
        menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homepage.setBackground(new java.awt.Color(255, 0, 255));
        homepage.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 204, 204)));
        homepage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(0, 102, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Home_26px_2.png"))); // NOI18N
        jLabel5.setText("   HOME PAGE");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homepage.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 5, 250, 50));

        menu.add(homepage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 340, 60));

        dashboard.setBackground(new java.awt.Color(108, 99, 255));
        dashboard.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 204, 204)));
        dashboard.setForeground(new java.awt.Color(255, 255, 255));
        dashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        dashboard.setFont(new java.awt.Font("Rockwell Nova Extra Bold", 1, 18)); // NOI18N
        dashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setBackground(new java.awt.Color(0, 102, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Library_26px_1.png"))); // NOI18N
        jLabel6.setText("   DASHBOARD");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dashboard.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 5, 250, 50));

        menu.add(dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 340, 60));

        jPanel25.setBackground(new java.awt.Color(108, 99, 255));
        jPanel25.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 204, 204)));
        jPanel25.setForeground(new java.awt.Color(255, 255, 255));
        jPanel25.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel25.setFont(new java.awt.Font("Rockwell Nova Extra Bold", 1, 18)); // NOI18N
        jPanel25.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel34.setBackground(new java.awt.Color(0, 102, 204));
        jPanel34.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 204, 204)));
        jPanel34.setForeground(new java.awt.Color(255, 255, 255));
        jPanel34.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel34.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jPanel34.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel25.add(jPanel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, -10, 340, -1));

        jLabel9.setBackground(new java.awt.Color(0, 102, 255));
        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Books_26px.png"))); // NOI18N
        jLabel9.setText("   ISSUED BOOKS RECORD");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel25.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 250, 50));

        menu.add(jPanel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 340, 60));

        jPanel14.setBackground(new java.awt.Color(108, 99, 255));
        jPanel14.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 204, 204)));
        jPanel14.setForeground(new java.awt.Color(255, 255, 255));
        jPanel14.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel14.setFont(new java.awt.Font("Rockwell Nova Extra Bold", 1, 18)); // NOI18N
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setBackground(new java.awt.Color(0, 102, 255));
        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Read_Online_26px.png"))); // NOI18N
        jLabel12.setText("   MANAGE STUDENTS");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jPanel14.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 5, 250, 50));

        menu.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 340, 60));

        jPanel32.setBackground(new java.awt.Color(108, 99, 255));
        jPanel32.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 204, 204)));
        jPanel32.setForeground(new java.awt.Color(255, 255, 255));
        jPanel32.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel32.setFont(new java.awt.Font("Rockwell Nova Extra Bold", 1, 18)); // NOI18N
        jPanel32.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(0, 102, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Book_26px.png"))); // NOI18N
        jLabel7.setText("   MANAGE BOOKS");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel32.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 5, 250, 50));

        menu.add(jPanel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 340, 60));

        jPanel33.setBackground(new java.awt.Color(108, 99, 255));
        jPanel33.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 204, 204)));
        jPanel33.setForeground(new java.awt.Color(255, 255, 255));
        jPanel33.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel33.setFont(new java.awt.Font("Rockwell Nova Extra Bold", 1, 18)); // NOI18N
        jPanel33.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setBackground(new java.awt.Color(0, 102, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Sell_26px.png"))); // NOI18N
        jLabel8.setText("   ISSUE BOOKS");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel33.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 5, 250, 50));

        menu.add(jPanel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 340, 60));

        jPanel28.setBackground(new java.awt.Color(108, 99, 255));
        jPanel28.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 204, 204)));
        jPanel28.setForeground(new java.awt.Color(255, 255, 255));
        jPanel28.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel28.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jPanel28.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Exit_26px_2.png"))); // NOI18N
        jLabel15.setText("  LOGOUT");
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel28.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 250, 50));

        menu.add(jPanel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 650, 340, 60));

        jPanel1.setBackground(new java.awt.Color(108, 99, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 204, 204)));
        jPanel1.setFont(new java.awt.Font("Rockwell Nova Extra Bold", 1, 18)); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setBackground(new java.awt.Color(0, 102, 255));
        jLabel14.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Return_Purchase_26px.png"))); // NOI18N
        jLabel14.setText("   RETURN BOOK");
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 5, 250, 50));

        menu.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 340, 60));

        jPanel4.setBackground(new java.awt.Color(108, 99, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 204, 204)));
        jPanel4.setFont(new java.awt.Font("Rockwell Nova Extra Bold", 1, 18)); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setBackground(new java.awt.Color(0, 102, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Conference_26px.png"))); // NOI18N
        jLabel10.setText("   DEFAULTERS");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 250, 50));

        jPanel5.setBackground(new java.awt.Color(0, 102, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 204, 204)));
        jPanel5.setFont(new java.awt.Font("Rockwell Nova Extra Bold", 1, 14)); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setBackground(new java.awt.Color(0, 102, 255));
        jLabel16.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("DEFAULTERS");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 300, 50));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 340, 60));

        menu.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 290, 60));

        jPanel6.setBackground(new java.awt.Color(108, 99, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 204, 204)));
        jPanel6.setFont(new java.awt.Font("Rockwell Nova Extra Bold", 1, 18)); // NOI18N
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_View_Details_26px.png"))); // NOI18N
        jLabel17.setText("   VIEW RECORDS");
        jLabel17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 5, 250, 50));

        menu.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 340, 60));

        jLabel13.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("ACTIONS");
        menu.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 70, -1));

        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 290, 960));

        main_component.setBackground(new java.awt.Color(204, 204, 204));
        main_component.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_People_50px.png"))); // NOI18N
        jLabel19.setText("   10");
        jPanel7.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 130, -1));

        jPanel8.setBackground(new java.awt.Color(204, 204, 204));
        jPanel8.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setText("10");
        jPanel8.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jPanel9.setBackground(new java.awt.Color(204, 204, 204));
        jPanel9.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setText("10");
        jPanel9.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jPanel10.setBackground(new java.awt.Color(204, 204, 204));
        jPanel10.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setText("10");
        jPanel10.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jPanel9.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 120, 80));

        jLabel24.setText("Books Count");
        jPanel9.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 70, 20));

        jPanel11.setBackground(new java.awt.Color(204, 204, 204));
        jPanel11.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setText("10");
        jPanel11.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jPanel12.setBackground(new java.awt.Color(204, 204, 204));
        jPanel12.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setText("10");
        jPanel12.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jPanel13.setBackground(new java.awt.Color(204, 204, 204));
        jPanel13.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setText("10");
        jPanel13.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jPanel15.setBackground(new java.awt.Color(204, 204, 204));
        jPanel15.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setText("10");
        jPanel15.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jPanel13.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 120, 80));

        jLabel30.setText("Books Count");
        jPanel13.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 70, 20));

        jPanel12.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 120, 80));

        jLabel31.setText("Books Count");
        jPanel12.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 70, 20));

        jPanel11.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 120, 80));

        jLabel32.setText("Books Count");
        jPanel11.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 70, 20));

        jPanel9.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 120, 80));

        jLabel33.setText("Books Count");
        jPanel9.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 70, 20));

        jPanel16.setBackground(new java.awt.Color(204, 204, 204));
        jPanel16.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel34.setText("10");
        jPanel16.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jPanel17.setBackground(new java.awt.Color(204, 204, 204));
        jPanel17.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel35.setText("10");
        jPanel17.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jPanel18.setBackground(new java.awt.Color(204, 204, 204));
        jPanel18.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel36.setText("10");
        jPanel18.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jPanel19.setBackground(new java.awt.Color(204, 204, 204));
        jPanel19.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel37.setText("10");
        jPanel19.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jPanel18.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 120, 80));

        jLabel38.setText("Books Count");
        jPanel18.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 70, 20));

        jPanel20.setBackground(new java.awt.Color(204, 204, 204));
        jPanel20.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel39.setText("10");
        jPanel20.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jPanel21.setBackground(new java.awt.Color(204, 204, 204));
        jPanel21.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel40.setText("10");
        jPanel21.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jPanel22.setBackground(new java.awt.Color(204, 204, 204));
        jPanel22.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel41.setText("10");
        jPanel22.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jPanel23.setBackground(new java.awt.Color(204, 204, 204));
        jPanel23.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanel23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel42.setText("10");
        jPanel23.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jPanel22.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 120, 80));

        jLabel43.setText("Books Count");
        jPanel22.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 70, 20));

        jPanel21.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 120, 80));

        jLabel44.setText("Books Count");
        jPanel21.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 70, 20));

        jPanel20.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 120, 80));

        jLabel45.setText("Books Count");
        jPanel20.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 70, 20));

        jPanel18.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 120, 80));

        jLabel46.setText("Books Count");
        jPanel18.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 70, 20));

        jPanel17.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 120, 80));

        jLabel47.setText("Books Count");
        jPanel17.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 70, 20));

        jPanel16.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 120, 80));

        jLabel48.setText("Books Count");
        jPanel16.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 70, 20));

        jPanel9.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 120, 80));

        jLabel49.setText("Books Count");
        jPanel9.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 70, 20));

        jPanel8.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 120, 80));

        jLabel25.setText("Books Count");
        jPanel8.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 70, 20));

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 120, 80));

        jLabel21.setText("Books Count");
        jPanel7.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 70, 20));

        main_component.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 150, 80));

        books_count.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        books_count.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        books_count.setText("STUDENTS DETAILS");
        main_component.add(books_count, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 150, 20));

        jPanel24.setBackground(new java.awt.Color(255, 255, 255));
        jPanel24.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanel24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel50.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_People_50px.png"))); // NOI18N
        jLabel50.setText("   10");
        jPanel24.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 130, -1));

        jPanel26.setBackground(new java.awt.Color(204, 204, 204));
        jPanel26.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanel26.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel51.setText("10");
        jPanel26.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jPanel27.setBackground(new java.awt.Color(204, 204, 204));
        jPanel27.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanel27.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel52.setText("10");
        jPanel27.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jPanel29.setBackground(new java.awt.Color(204, 204, 204));
        jPanel29.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanel29.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel53.setText("10");
        jPanel29.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jPanel27.add(jPanel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 120, 80));

        jLabel54.setText("Books Count");
        jPanel27.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 70, 20));

        jPanel30.setBackground(new java.awt.Color(204, 204, 204));
        jPanel30.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanel30.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel55.setText("10");
        jPanel30.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jPanel31.setBackground(new java.awt.Color(204, 204, 204));
        jPanel31.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanel31.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel56.setText("10");
        jPanel31.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jPanel35.setBackground(new java.awt.Color(204, 204, 204));
        jPanel35.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanel35.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel57.setText("10");
        jPanel35.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jPanel36.setBackground(new java.awt.Color(204, 204, 204));
        jPanel36.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanel36.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel58.setText("10");
        jPanel36.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jPanel35.add(jPanel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 120, 80));

        jLabel59.setText("Books Count");
        jPanel35.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 70, 20));

        jPanel31.add(jPanel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 120, 80));

        jLabel60.setText("Books Count");
        jPanel31.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 70, 20));

        jPanel30.add(jPanel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 120, 80));

        jLabel61.setText("Books Count");
        jPanel30.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 70, 20));

        jPanel27.add(jPanel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 120, 80));

        jLabel62.setText("Books Count");
        jPanel27.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 70, 20));

        jPanel37.setBackground(new java.awt.Color(204, 204, 204));
        jPanel37.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanel37.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel63.setText("10");
        jPanel37.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jPanel38.setBackground(new java.awt.Color(204, 204, 204));
        jPanel38.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanel38.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel64.setText("10");
        jPanel38.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jPanel39.setBackground(new java.awt.Color(204, 204, 204));
        jPanel39.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanel39.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel65.setText("10");
        jPanel39.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jPanel40.setBackground(new java.awt.Color(204, 204, 204));
        jPanel40.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanel40.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel66.setText("10");
        jPanel40.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jPanel39.add(jPanel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 120, 80));

        jLabel67.setText("Books Count");
        jPanel39.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 70, 20));

        jPanel41.setBackground(new java.awt.Color(204, 204, 204));
        jPanel41.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanel41.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel68.setText("10");
        jPanel41.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jPanel42.setBackground(new java.awt.Color(204, 204, 204));
        jPanel42.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanel42.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel69.setText("10");
        jPanel42.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jPanel43.setBackground(new java.awt.Color(204, 204, 204));
        jPanel43.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanel43.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel70.setText("10");
        jPanel43.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jPanel44.setBackground(new java.awt.Color(204, 204, 204));
        jPanel44.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanel44.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel71.setText("10");
        jPanel44.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jPanel43.add(jPanel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 120, 80));

        jLabel72.setText("Books Count");
        jPanel43.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 70, 20));

        jPanel42.add(jPanel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 120, 80));

        jLabel73.setText("Books Count");
        jPanel42.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 70, 20));

        jPanel41.add(jPanel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 120, 80));

        jLabel74.setText("Books Count");
        jPanel41.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 70, 20));

        jPanel39.add(jPanel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 120, 80));

        jLabel75.setText("Books Count");
        jPanel39.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 70, 20));

        jPanel38.add(jPanel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 120, 80));

        jLabel76.setText("Books Count");
        jPanel38.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 70, 20));

        jPanel37.add(jPanel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 120, 80));

        jLabel77.setText("Books Count");
        jPanel37.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 70, 20));

        jPanel27.add(jPanel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 120, 80));

        jLabel78.setText("Books Count");
        jPanel27.add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 70, 20));

        jPanel26.add(jPanel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 120, 80));

        jLabel79.setText("Books Count");
        jPanel26.add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 70, 20));

        jPanel24.add(jPanel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 120, 80));

        jLabel80.setText("Books Count");
        jPanel24.add(jLabel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 70, 20));

        main_component.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 150, 80));

        jPanel45.setBackground(new java.awt.Color(255, 255, 255));
        jPanel45.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanel45.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel81.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel81.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_People_50px.png"))); // NOI18N
        jLabel81.setText("   10");
        jPanel45.add(jLabel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 130, -1));

        jPanel46.setBackground(new java.awt.Color(204, 204, 204));
        jPanel46.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanel46.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel82.setText("10");
        jPanel46.add(jLabel82, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jPanel47.setBackground(new java.awt.Color(204, 204, 204));
        jPanel47.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanel47.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel83.setText("10");
        jPanel47.add(jLabel83, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jPanel48.setBackground(new java.awt.Color(204, 204, 204));
        jPanel48.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanel48.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel84.setText("10");
        jPanel48.add(jLabel84, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jPanel47.add(jPanel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 120, 80));

        jLabel85.setText("Books Count");
        jPanel47.add(jLabel85, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 70, 20));

        jPanel49.setBackground(new java.awt.Color(204, 204, 204));
        jPanel49.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanel49.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel86.setText("10");
        jPanel49.add(jLabel86, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jPanel50.setBackground(new java.awt.Color(204, 204, 204));
        jPanel50.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanel50.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel87.setText("10");
        jPanel50.add(jLabel87, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jPanel51.setBackground(new java.awt.Color(204, 204, 204));
        jPanel51.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanel51.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel88.setText("10");
        jPanel51.add(jLabel88, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jPanel52.setBackground(new java.awt.Color(204, 204, 204));
        jPanel52.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanel52.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel89.setText("10");
        jPanel52.add(jLabel89, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jPanel51.add(jPanel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 120, 80));

        jLabel90.setText("Books Count");
        jPanel51.add(jLabel90, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 70, 20));

        jPanel50.add(jPanel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 120, 80));

        jLabel91.setText("Books Count");
        jPanel50.add(jLabel91, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 70, 20));

        jPanel49.add(jPanel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 120, 80));

        jLabel92.setText("Books Count");
        jPanel49.add(jLabel92, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 70, 20));

        jPanel47.add(jPanel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 120, 80));

        jLabel93.setText("Books Count");
        jPanel47.add(jLabel93, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 70, 20));

        jPanel53.setBackground(new java.awt.Color(204, 204, 204));
        jPanel53.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanel53.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel94.setText("10");
        jPanel53.add(jLabel94, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jPanel54.setBackground(new java.awt.Color(204, 204, 204));
        jPanel54.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanel54.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel95.setText("10");
        jPanel54.add(jLabel95, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jPanel55.setBackground(new java.awt.Color(204, 204, 204));
        jPanel55.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanel55.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel96.setText("10");
        jPanel55.add(jLabel96, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jPanel56.setBackground(new java.awt.Color(204, 204, 204));
        jPanel56.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanel56.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel97.setText("10");
        jPanel56.add(jLabel97, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jPanel55.add(jPanel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 120, 80));

        jLabel98.setText("Books Count");
        jPanel55.add(jLabel98, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 70, 20));

        jPanel57.setBackground(new java.awt.Color(204, 204, 204));
        jPanel57.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanel57.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel99.setText("10");
        jPanel57.add(jLabel99, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jPanel58.setBackground(new java.awt.Color(204, 204, 204));
        jPanel58.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanel58.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel100.setText("10");
        jPanel58.add(jLabel100, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jPanel59.setBackground(new java.awt.Color(204, 204, 204));
        jPanel59.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanel59.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel101.setText("10");
        jPanel59.add(jLabel101, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jPanel60.setBackground(new java.awt.Color(204, 204, 204));
        jPanel60.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanel60.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel102.setText("10");
        jPanel60.add(jLabel102, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jPanel59.add(jPanel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 120, 80));

        jLabel103.setText("Books Count");
        jPanel59.add(jLabel103, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 70, 20));

        jPanel58.add(jPanel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 120, 80));

        jLabel104.setText("Books Count");
        jPanel58.add(jLabel104, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 70, 20));

        jPanel57.add(jPanel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 120, 80));

        jLabel105.setText("Books Count");
        jPanel57.add(jLabel105, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 70, 20));

        jPanel55.add(jPanel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 120, 80));

        jLabel106.setText("Books Count");
        jPanel55.add(jLabel106, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 70, 20));

        jPanel54.add(jPanel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 120, 80));

        jLabel107.setText("Books Count");
        jPanel54.add(jLabel107, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 70, 20));

        jPanel53.add(jPanel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 120, 80));

        jLabel108.setText("Books Count");
        jPanel53.add(jLabel108, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 70, 20));

        jPanel47.add(jPanel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 120, 80));

        jLabel109.setText("Books Count");
        jPanel47.add(jLabel109, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 70, 20));

        jPanel46.add(jPanel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 120, 80));

        jLabel110.setText("Books Count");
        jPanel46.add(jLabel110, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 70, 20));

        jPanel45.add(jPanel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 120, 80));

        jLabel111.setText("Books Count");
        jPanel45.add(jLabel111, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 70, 20));

        main_component.add(jPanel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 150, 80));

        students_count.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        students_count.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        students_count.setText("No. OF STUDENTS");
        main_component.add(students_count, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 150, 20));

        defaulters.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        defaulters.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        defaulters.setText("Defaulters");
        main_component.add(defaulters, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, 150, 20));

        jPanel61.setBackground(new java.awt.Color(255, 255, 255));
        jPanel61.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanel61.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel112.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel112.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_People_50px.png"))); // NOI18N
        jLabel112.setText("   10");
        jPanel61.add(jLabel112, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 130, -1));

        jPanel62.setBackground(new java.awt.Color(204, 204, 204));
        jPanel62.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanel62.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel113.setText("10");
        jPanel62.add(jLabel113, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jPanel63.setBackground(new java.awt.Color(204, 204, 204));
        jPanel63.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanel63.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel114.setText("10");
        jPanel63.add(jLabel114, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jPanel64.setBackground(new java.awt.Color(204, 204, 204));
        jPanel64.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanel64.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel115.setText("10");
        jPanel64.add(jLabel115, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jPanel63.add(jPanel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 120, 80));

        jLabel116.setText("Books Count");
        jPanel63.add(jLabel116, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 70, 20));

        jPanel65.setBackground(new java.awt.Color(204, 204, 204));
        jPanel65.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanel65.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel117.setText("10");
        jPanel65.add(jLabel117, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jPanel66.setBackground(new java.awt.Color(204, 204, 204));
        jPanel66.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanel66.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel118.setText("10");
        jPanel66.add(jLabel118, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jPanel67.setBackground(new java.awt.Color(204, 204, 204));
        jPanel67.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanel67.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel119.setText("10");
        jPanel67.add(jLabel119, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jPanel68.setBackground(new java.awt.Color(204, 204, 204));
        jPanel68.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanel68.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel120.setText("10");
        jPanel68.add(jLabel120, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jPanel67.add(jPanel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 120, 80));

        jLabel121.setText("Books Count");
        jPanel67.add(jLabel121, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 70, 20));

        jPanel66.add(jPanel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 120, 80));

        jLabel122.setText("Books Count");
        jPanel66.add(jLabel122, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 70, 20));

        jPanel65.add(jPanel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 120, 80));

        jLabel123.setText("Books Count");
        jPanel65.add(jLabel123, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 70, 20));

        jPanel63.add(jPanel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 120, 80));

        jLabel124.setText("Books Count");
        jPanel63.add(jLabel124, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 70, 20));

        jPanel69.setBackground(new java.awt.Color(204, 204, 204));
        jPanel69.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanel69.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel125.setText("10");
        jPanel69.add(jLabel125, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jPanel70.setBackground(new java.awt.Color(204, 204, 204));
        jPanel70.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanel70.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel126.setText("10");
        jPanel70.add(jLabel126, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jPanel71.setBackground(new java.awt.Color(204, 204, 204));
        jPanel71.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanel71.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel127.setText("10");
        jPanel71.add(jLabel127, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jPanel72.setBackground(new java.awt.Color(204, 204, 204));
        jPanel72.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanel72.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel128.setText("10");
        jPanel72.add(jLabel128, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jPanel71.add(jPanel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 120, 80));

        jLabel129.setText("Books Count");
        jPanel71.add(jLabel129, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 70, 20));

        jPanel73.setBackground(new java.awt.Color(204, 204, 204));
        jPanel73.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanel73.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel130.setText("10");
        jPanel73.add(jLabel130, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jPanel74.setBackground(new java.awt.Color(204, 204, 204));
        jPanel74.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanel74.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel131.setText("10");
        jPanel74.add(jLabel131, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jPanel75.setBackground(new java.awt.Color(204, 204, 204));
        jPanel75.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanel75.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel132.setText("10");
        jPanel75.add(jLabel132, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jPanel76.setBackground(new java.awt.Color(204, 204, 204));
        jPanel76.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanel76.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel133.setText("10");
        jPanel76.add(jLabel133, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jPanel75.add(jPanel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 120, 80));

        jLabel134.setText("Books Count");
        jPanel75.add(jLabel134, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 70, 20));

        jPanel74.add(jPanel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 120, 80));

        jLabel135.setText("Books Count");
        jPanel74.add(jLabel135, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 70, 20));

        jPanel73.add(jPanel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 120, 80));

        jLabel136.setText("Books Count");
        jPanel73.add(jLabel136, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 70, 20));

        jPanel71.add(jPanel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 120, 80));

        jLabel137.setText("Books Count");
        jPanel71.add(jLabel137, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 70, 20));

        jPanel70.add(jPanel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 120, 80));

        jLabel138.setText("Books Count");
        jPanel70.add(jLabel138, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 70, 20));

        jPanel69.add(jPanel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 120, 80));

        jLabel139.setText("Books Count");
        jPanel69.add(jLabel139, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 70, 20));

        jPanel63.add(jPanel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 120, 80));

        jLabel140.setText("Books Count");
        jPanel63.add(jLabel140, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 70, 20));

        jPanel62.add(jPanel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 120, 80));

        jLabel141.setText("Books Count");
        jPanel62.add(jLabel141, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 70, 20));

        jPanel61.add(jPanel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 120, 80));

        jLabel142.setText("Books Count");
        jPanel61.add(jLabel142, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 70, 20));

        main_component.add(jPanel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 40, 150, 80));

        IssuedBooks.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        IssuedBooks.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IssuedBooks.setText("Issued Books");
        main_component.add(IssuedBooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 150, 20));

        rSTableMetro1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1590", "IJAMY VINCENT", "2", "WEST"},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ADMIN NO.", "NAME", "CLASS", "STREAM"
            }
        ));
        rSTableMetro1.setColorBackgoundHead(new java.awt.Color(255, 0, 153));
        rSTableMetro1.setColorFilasBackgound2(new java.awt.Color(204, 204, 255));
        rSTableMetro1.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        rSTableMetro1.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        rSTableMetro1.setRowHeight(25);
        jScrollPane1.setViewportView(rSTableMetro1);

        main_component.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 720, 180));

        books_count1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        books_count1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        books_count1.setText("Books Count");
        main_component.add(books_count1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 150, 20));

        books_count2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        books_count2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        books_count2.setText("BOOKS DETAILS");
        main_component.add(books_count2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 150, 20));

        rSTableMetro2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"7898", "CHEM FORM 2", "MALDRINE", "500"},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "BOOK ID", "TITLE", "AUTHOR", "QUANTITY"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        rSTableMetro2.setColorBackgoundHead(new java.awt.Color(255, 0, 153));
        rSTableMetro2.setColorFilasBackgound2(new java.awt.Color(204, 204, 255));
        rSTableMetro2.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        rSTableMetro2.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        rSTableMetro2.setRowHeight(25);
        jScrollPane2.setViewportView(rSTableMetro2);

        main_component.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 720, 180));

        pieChartPanel.setLayout(new java.awt.BorderLayout());
        main_component.add(pieChartPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 40, 530, 440));

        getContentPane().add(main_component, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 1290, 720));

        setSize(new java.awt.Dimension(1578, 781));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        ManageBooks books = new ManageBooks();
        books.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        ManageStudents students = new ManageStudents();
        students.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        IssueBooks issuebooks = new IssueBooks();
        issuebooks.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        ReturnBooks returnbooks = new ReturnBooks();
        returnbooks.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
      PendingBooks pendingbooks = new PendingBooks();
        pendingbooks.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        Records records = new Records();
        records.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
          Defaulters defaulter = new Defaulters();
        defaulter.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel10MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IssuedBooks;
    private javax.swing.JLabel books_count;
    private javax.swing.JLabel books_count1;
    private javax.swing.JLabel books_count2;
    private javax.swing.JPanel dashboard;
    private javax.swing.JLabel defaulters;
    private javax.swing.JPanel header;
    private javax.swing.JPanel homepage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel110;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel114;
    private javax.swing.JLabel jLabel115;
    private javax.swing.JLabel jLabel116;
    private javax.swing.JLabel jLabel117;
    private javax.swing.JLabel jLabel118;
    private javax.swing.JLabel jLabel119;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel120;
    private javax.swing.JLabel jLabel121;
    private javax.swing.JLabel jLabel122;
    private javax.swing.JLabel jLabel123;
    private javax.swing.JLabel jLabel124;
    private javax.swing.JLabel jLabel125;
    private javax.swing.JLabel jLabel126;
    private javax.swing.JLabel jLabel127;
    private javax.swing.JLabel jLabel128;
    private javax.swing.JLabel jLabel129;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel130;
    private javax.swing.JLabel jLabel131;
    private javax.swing.JLabel jLabel132;
    private javax.swing.JLabel jLabel133;
    private javax.swing.JLabel jLabel134;
    private javax.swing.JLabel jLabel135;
    private javax.swing.JLabel jLabel136;
    private javax.swing.JLabel jLabel137;
    private javax.swing.JLabel jLabel138;
    private javax.swing.JLabel jLabel139;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel140;
    private javax.swing.JLabel jLabel141;
    private javax.swing.JLabel jLabel142;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JPanel jPanel46;
    private javax.swing.JPanel jPanel47;
    private javax.swing.JPanel jPanel48;
    private javax.swing.JPanel jPanel49;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel50;
    private javax.swing.JPanel jPanel51;
    private javax.swing.JPanel jPanel52;
    private javax.swing.JPanel jPanel53;
    private javax.swing.JPanel jPanel54;
    private javax.swing.JPanel jPanel55;
    private javax.swing.JPanel jPanel56;
    private javax.swing.JPanel jPanel57;
    private javax.swing.JPanel jPanel58;
    private javax.swing.JPanel jPanel59;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel60;
    private javax.swing.JPanel jPanel61;
    private javax.swing.JPanel jPanel62;
    private javax.swing.JPanel jPanel63;
    private javax.swing.JPanel jPanel64;
    private javax.swing.JPanel jPanel65;
    private javax.swing.JPanel jPanel66;
    private javax.swing.JPanel jPanel67;
    private javax.swing.JPanel jPanel68;
    private javax.swing.JPanel jPanel69;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel70;
    private javax.swing.JPanel jPanel71;
    private javax.swing.JPanel jPanel72;
    private javax.swing.JPanel jPanel73;
    private javax.swing.JPanel jPanel74;
    private javax.swing.JPanel jPanel75;
    private javax.swing.JPanel jPanel76;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel main_component;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel pieChartPanel;
    private rojeru_san.complementos.RSTableMetro rSTableMetro1;
    private rojeru_san.complementos.RSTableMetro rSTableMetro2;
    private javax.swing.JLabel students_count;
    // End of variables declaration//GEN-END:variables
}
