 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jFrame;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author IJAMY
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Login() {
        initComponents();
    }

         //validate LOGIN
    public boolean validateLogin(){
        String name = input_username.getText();
        String pwd = input_password.getText();
        
          if (name.equals("")){
           JOptionPane.showMessageDialog(this, "please enter your username");
           return false;
        }        
        if (pwd.equals("")){
           JOptionPane.showMessageDialog(this, "please enter your password");
           return false;
        }  
        return true;
    }

//    verify users login
    public void Login(){
        String name = input_username.getText();
        String pwd = input_password.getText();
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
             Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/library_management_system","root","");
            PreparedStatement pst= con.prepareStatement("select * from users where name=? and password = ?");
            
             pst.setString(1, name);
            pst.setString(2, pwd);
            
            ResultSet rs = pst.executeQuery();
            if(rs.next()){
                JOptionPane.showMessageDialog(this, "login successfull");
                
                HomePage home = new HomePage();
                home.setVisible(true);
                this.dispose();
            } else{
                
            }
        } catch(ClassNotFoundException | SQLException e){
          JOptionPane.showMessageDialog(this, "wrong credintials");
                  
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        input_password = new app.bolivia.swing.JCTextField();
        input_username = new app.bolivia.swing.JCTextField();
        login_Btn = new necesario.RSMaterialButtonCircle();
        register_Btn = new necesario.RSMaterialButtonCircle();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 0, 153));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(108, 99, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        title.setForeground(new java.awt.Color(10, 10, 10));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("LOGIN PAGE");
        title.setToolTipText("REGISTER");
        jPanel2.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 430, 40));

        password.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        password.setForeground(new java.awt.Color(240, 240, 240));
        password.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        password.setText("PASSWORD");
        password.setAlignmentY(10.0F);
        jPanel2.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 300, 30));

        username.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        username.setForeground(new java.awt.Color(240, 240, 240));
        username.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        username.setText("USERNAME");
        username.setAlignmentY(10.0F);
        jPanel2.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 300, 30));

        input_password.setBackground(new java.awt.Color(108, 99, 255));
        input_password.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        input_password.setForeground(new java.awt.Color(100, 240, 240));
        input_password.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        input_password.setText("1234");
        input_password.setCaretColor(new java.awt.Color(255, 255, 255));
        input_password.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        input_password.setPhColor(new java.awt.Color(255, 255, 0));
        input_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_passwordActionPerformed(evt);
            }
        });
        jPanel2.add(input_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 300, 30));

        input_username.setBackground(new java.awt.Color(108, 99, 255));
        input_username.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        input_username.setForeground(new java.awt.Color(100, 240, 240));
        input_username.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        input_username.setText("ijamy");
        input_username.setCaretColor(new java.awt.Color(255, 255, 255));
        input_username.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        input_username.setPhColor(new java.awt.Color(255, 255, 0));
        input_username.setPlaceholder("please enter your name");
        input_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_usernameFocusLost(evt);
            }
        });
        jPanel2.add(input_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 300, 30));

        login_Btn.setBackground(new java.awt.Color(102, 255, 0));
        login_Btn.setText("LOGIN");
        login_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_BtnActionPerformed(evt);
            }
        });
        jPanel2.add(login_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 190, 50));

        register_Btn.setBackground(new java.awt.Color(0, 0, 255));
        register_Btn.setText("SIGN UP");
        register_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_BtnActionPerformed(evt);
            }
        });
        jPanel2.add(register_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, 190, 50));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Secure_50px.png"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 50, 60));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 50, 60));

        jLabel2.setBackground(new java.awt.Color(108, 99, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("LUSENGELI SEC SCHOOL");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 26, 400, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 420, 570));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/undraw_mathematics_4otb.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 570));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 570));

        setSize(new java.awt.Dimension(853, 580));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void register_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_BtnActionPerformed

    }//GEN-LAST:event_register_BtnActionPerformed

    private void login_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_BtnActionPerformed
        validateLogin();
    }//GEN-LAST:event_login_BtnActionPerformed

    private void input_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_usernameFocusLost

    }//GEN-LAST:event_input_usernameFocusLost

    private void input_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_passwordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private app.bolivia.swing.JCTextField input_password;
    private app.bolivia.swing.JCTextField input_username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private necesario.RSMaterialButtonCircle login_Btn;
    private javax.swing.JLabel password;
    private necesario.RSMaterialButtonCircle register_Btn;
    private javax.swing.JLabel title;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
