/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jFrame;

/**
 *
 * @author IJAMY
 */
public class ManageStudents extends javax.swing.JFrame {

    /**
     * Creates new form ManageStudents
     */
    public ManageStudents() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        rSTableMetro2 = new rojeru_san.complementos.RSTableMetro();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        input_BookId = new app.bolivia.swing.JCTextField();
        username2 = new javax.swing.JLabel();
        input_BookAuthor = new app.bolivia.swing.JCTextField();
        username3 = new javax.swing.JLabel();
        input_BookTitle = new app.bolivia.swing.JCTextField();
        username4 = new javax.swing.JLabel();
        input_BookQuantity = new app.bolivia.swing.JCTextField();
        login_Btn = new necesario.RSMaterialButtonCircle();
        login_Btn1 = new necesario.RSMaterialButtonCircle();
        login_Btn2 = new necesario.RSMaterialButtonCircle();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(143, 290));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSTableMetro2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"7898", "CHEM FORM 2", "MALDRINE", "500"},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ADMIN NO.", "NAME", "FORM", "STREAM"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        rSTableMetro2.setColorBackgoundHead(new java.awt.Color(255, 0, 153));
        rSTableMetro2.setColorFilasBackgound2(new java.awt.Color(204, 204, 255));
        rSTableMetro2.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        rSTableMetro2.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        rSTableMetro2.setRowHeight(25);
        rSTableMetro2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSTableMetro2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(rSTableMetro2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 1200, 200));

        jLabel6.setBackground(new java.awt.Color(255, 51, 51));
        jLabel6.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 51, 51));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Books_52px_1.png"))); // NOI18N
        jLabel6.setText("    STUDENT DATA");
        jLabel6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 0, new java.awt.Color(255, 51, 51)));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 280, 70));

        jPanel2.setBackground(new java.awt.Color(108, 99, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(1400, 290));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(242, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Rewind_48px.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 70, 30));

        jPanel4.setBackground(new java.awt.Color(242, 51, 51));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Rewind_48px.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 70, 30));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 30));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 30));

        username.setBackground(new java.awt.Color(255, 255, 255));
        username.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        username.setForeground(new java.awt.Color(240, 240, 240));
        username.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        username.setText("ADMIN NO.");
        username.setAlignmentY(10.0F);
        jPanel2.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 300, 30));

        input_BookId.setBackground(new java.awt.Color(108, 99, 255));
        input_BookId.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        input_BookId.setForeground(java.awt.Color.cyan);
        input_BookId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        input_BookId.setCaretColor(new java.awt.Color(255, 255, 255));
        input_BookId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        input_BookId.setPhColor(new java.awt.Color(255, 255, 0));
        input_BookId.setPlaceholder("please enter student' admin no.");
        input_BookId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_BookIdFocusLost(evt);
            }
        });
        input_BookId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_BookIdActionPerformed(evt);
            }
        });
        jPanel2.add(input_BookId, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 300, 30));

        username2.setBackground(new java.awt.Color(255, 255, 255));
        username2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        username2.setForeground(new java.awt.Color(240, 240, 240));
        username2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        username2.setText("FORM");
        username2.setAlignmentY(10.0F);
        jPanel2.add(username2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 100, 300, 30));

        input_BookAuthor.setBackground(new java.awt.Color(108, 99, 255));
        input_BookAuthor.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        input_BookAuthor.setForeground(java.awt.Color.cyan);
        input_BookAuthor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        input_BookAuthor.setCaretColor(new java.awt.Color(255, 255, 255));
        input_BookAuthor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        input_BookAuthor.setPhColor(new java.awt.Color(255, 255, 0));
        input_BookAuthor.setPlaceholder("please enter class");
        input_BookAuthor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_BookAuthorFocusLost(evt);
            }
        });
        jPanel2.add(input_BookAuthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 150, 300, 30));

        username3.setBackground(new java.awt.Color(255, 255, 255));
        username3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        username3.setForeground(new java.awt.Color(240, 240, 240));
        username3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        username3.setText("NAME");
        username3.setAlignmentY(10.0F);
        jPanel2.add(username3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, 300, 30));

        input_BookTitle.setBackground(new java.awt.Color(108, 99, 255));
        input_BookTitle.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        input_BookTitle.setForeground(java.awt.Color.cyan);
        input_BookTitle.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        input_BookTitle.setCaretColor(new java.awt.Color(255, 255, 255));
        input_BookTitle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        input_BookTitle.setPhColor(new java.awt.Color(255, 255, 0));
        input_BookTitle.setPlaceholder("please enter student's name");
        input_BookTitle.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_BookTitleFocusLost(evt);
            }
        });
        jPanel2.add(input_BookTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, 300, 30));

        username4.setBackground(new java.awt.Color(255, 255, 255));
        username4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        username4.setForeground(new java.awt.Color(240, 240, 240));
        username4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        username4.setText("STREAM");
        username4.setAlignmentY(10.0F);
        jPanel2.add(username4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 100, 300, 30));

        input_BookQuantity.setBackground(new java.awt.Color(108, 99, 255));
        input_BookQuantity.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        input_BookQuantity.setForeground(java.awt.Color.cyan);
        input_BookQuantity.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        input_BookQuantity.setCaretColor(new java.awt.Color(255, 255, 255));
        input_BookQuantity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        input_BookQuantity.setPhColor(new java.awt.Color(255, 255, 0));
        input_BookQuantity.setPlaceholder("please enter your stream");
        input_BookQuantity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_BookQuantityFocusLost(evt);
            }
        });
        jPanel2.add(input_BookQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 150, 300, 30));

        login_Btn.setBackground(new java.awt.Color(62, 32, 255));
        login_Btn.setText("ADD");
        login_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_BtnActionPerformed(evt);
            }
        });
        jPanel2.add(login_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 110, 40));
        login_Btn.getAccessibleContext().setAccessibleName("");

        login_Btn1.setBackground(new java.awt.Color(255, 29, 54));
        login_Btn1.setText("DELETE");
        login_Btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_Btn1ActionPerformed(evt);
            }
        });
        jPanel2.add(login_Btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 250, 140, 40));
        login_Btn1.getAccessibleContext().setAccessibleName("");

        login_Btn2.setBackground(new java.awt.Color(17, 224, 21));
        login_Btn2.setText("UPDATE");
        login_Btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_Btn2ActionPerformed(evt);
            }
        });
        jPanel2.add(login_Btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 250, 130, 40));
        login_Btn2.getAccessibleContext().setAccessibleName("");

        jPanel5.setBackground(new java.awt.Color(102, 102, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(0, 51, 204));
        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("x");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 20, 40));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1540, 0, 40, 40));

        jLabel4.setBackground(new java.awt.Color(51, 255, 0));
        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 255, 0));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Books_52px_1.png"))); // NOI18N
        jLabel4.setText("   ADMIN PANEL");
        jLabel4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 0, new java.awt.Color(255, 51, 51)));
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 0, 280, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1580, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1580, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 307, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 536, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void rSTableMetro2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSTableMetro2MouseClicked
        // int rowNo = tableBookDetails.getSelectedRow();    // TODO add your handling code here:
    }//GEN-LAST:event_rSTableMetro2MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        HomePage home = new HomePage();
        home.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void input_BookIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_BookIdFocusLost
        //        if (checkDublicateUsers()== true){
            //            JOptionPane.showMessageDialog(this,"user already exist");
            //        }
    }//GEN-LAST:event_input_BookIdFocusLost

    private void input_BookIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_BookIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_BookIdActionPerformed

    private void input_BookAuthorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_BookAuthorFocusLost
        //        if (checkDublicateUsers()== true){
            //            JOptionPane.showMessageDialog(this,"user already exist");
            //        }
    }//GEN-LAST:event_input_BookAuthorFocusLost

    private void input_BookTitleFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_BookTitleFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_input_BookTitleFocusLost

    private void input_BookQuantityFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_BookQuantityFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_input_BookQuantityFocusLost

    private void login_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_BtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_login_BtnActionPerformed

    private void login_Btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_Btn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_login_Btn1ActionPerformed

    private void login_Btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_Btn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_login_Btn2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageStudents().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private app.bolivia.swing.JCTextField input_BookAuthor;
    private app.bolivia.swing.JCTextField input_BookId;
    private app.bolivia.swing.JCTextField input_BookQuantity;
    private app.bolivia.swing.JCTextField input_BookTitle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private necesario.RSMaterialButtonCircle login_Btn;
    private necesario.RSMaterialButtonCircle login_Btn1;
    private necesario.RSMaterialButtonCircle login_Btn2;
    private rojeru_san.complementos.RSTableMetro rSTableMetro2;
    private javax.swing.JLabel username;
    private javax.swing.JLabel username2;
    private javax.swing.JLabel username3;
    private javax.swing.JLabel username4;
    // End of variables declaration//GEN-END:variables
}
