 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jFrame;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author IJAMY
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }
   public boolean insertRegisterDetails(){
        String name = input_username.getText();
        String pwd = input_password.getText();
        String mail = input_email.getText();
        String phone = input_contact.getText();
        String staffid = input_staff_id.getText();
        
        
  
        try {
            Connection con = DBConnection.getConnection();
            String sql = "insert into users(name,password,email,contact,staff_id) values(?,?,?,?,?)";
            PreparedStatement pst= con.prepareStatement(sql);

            pst.setString(1, name);
            pst.setString(2, pwd);
            pst.setString(3, mail);
            pst.setString(4, phone);
            pst.setString(5, staffid);
       

            int updatedRowCount = pst.executeUpdate();

            if (updatedRowCount> 0 ){
                JOptionPane.showMessageDialog(this, "registration succefull");
                Login login = new Login();
                login.setVisible(true);
                dispose();
            } else {
                JOptionPane.showMessageDialog(this, "registration failed");
            }
        } catch(HeadlessException | SQLException e){
        }
        return false;

  
    }
         //validate Register
   
    public boolean validateRegister(){
        String name = input_username.getText();
        String pwd = input_password.getText();
        String mail = input_email.getText();
        String phone = input_contact.getText();
        String staffid = input_staff_id.getText();
        
        if (name.equals("")){
           JOptionPane.showInputDialog(this, "please enter your name");
           return false;
        }        
        if (pwd.equals("")){
           JOptionPane.showInputDialog(this, "please enter your password");
           return false;
        }        
        if (mail.equals("") || !mail.matches("^.+@.+\\..+$")){
           JOptionPane.showInputDialog(this, "please enter a valid email");
           return false;
        }        
        if (phone.equals("")){
           JOptionPane.showInputDialog(this, "please enter your phone number");
           return false;
        }        
        if (staffid.equals("")){
           JOptionPane.showInputDialog(this, "please enter your staff ID number");
           return false;
        }
        
        return true;
        }
        //check is there are dublicate users in the database

    public boolean checkDublicateUsers(){
            String name = input_username.getText();
            boolean isExist= false;
            
              try {
              Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/library_management_system","root","");
         
                PreparedStatement pst = con.prepareStatement("select * from users where name =?");
                pst.setString(1,name);
                
                ResultSet rs = pst.executeQuery();
                
                isExist = rs.next();
         
         
              } catch(ClassNotFoundException | SQLException e){
        }
         return isExist;   
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        school_title = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        contact = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        staff_id = new javax.swing.JLabel();
        input_contact = new app.bolivia.swing.JCTextField();
        input_password = new app.bolivia.swing.JCTextField();
        input_staff_id = new app.bolivia.swing.JCTextField();
        input_email = new app.bolivia.swing.JCTextField();
        input_username = new app.bolivia.swing.JCTextField();
        login_Btn = new necesario.RSMaterialButtonCircle();
        register_Btn = new necesario.RSMaterialButtonCircle();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 0, 153));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/undraw_Educator_re_ju47.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 610, 590));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(154, 40, 240));
        jLabel4.setText("LIBRARY MANAGEMENT SYSTEM");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 360, 60));

        jLabel5.setText("jLabel1");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 40, -1, -1));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setText("EMAIL :   SANDAJIVINCENT@GMAIL.COM");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 300, 30));

        jLabel6.setText("@2022 ALL RIGHTS RESERVED");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 170, 30));

        jLabel7.setText("DEVELOPED BY :   IJAMY VINCENT");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 210, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 640, 620, 110));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, 0, 710, 830));

        jPanel2.setBackground(new java.awt.Color(108, 99, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        school_title.setBackground(new java.awt.Color(108, 99, 255));
        school_title.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        school_title.setForeground(new java.awt.Color(255, 255, 255));
        school_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        school_title.setText("LUSENGELI SEC SCHOOL");
        school_title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(school_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 400, 40));

        title.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        title.setForeground(new java.awt.Color(10, 10, 10));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("REGISTER");
        title.setToolTipText("REGISTER");
        title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 400, 40));

        password.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        password.setForeground(new java.awt.Color(240, 240, 240));
        password.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        password.setText("PASSWORD");
        password.setAlignmentY(10.0F);
        jPanel2.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, 300, 30));

        username.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        username.setForeground(new java.awt.Color(240, 240, 240));
        username.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        username.setText("USERNAME");
        username.setAlignmentY(10.0F);
        jPanel2.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 300, 30));

        contact.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        contact.setForeground(new java.awt.Color(240, 240, 240));
        contact.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        contact.setText("CONTACT");
        contact.setAlignmentY(10.0F);
        jPanel2.add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 480, 300, 30));

        email.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        email.setForeground(new java.awt.Color(240, 240, 240));
        email.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        email.setText("EMAIL");
        email.setAlignmentY(10.0F);
        jPanel2.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 300, 30));

        staff_id.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        staff_id.setForeground(new java.awt.Color(240, 240, 240));
        staff_id.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        staff_id.setText("STAFF ID");
        staff_id.setAlignmentY(10.0F);
        jPanel2.add(staff_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 300, 30));

        input_contact.setBackground(new java.awt.Color(108, 99, 255));
        input_contact.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        input_contact.setForeground(new java.awt.Color(100, 240, 240));
        input_contact.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        input_contact.setText("1234567890");
        input_contact.setCaretColor(new java.awt.Color(255, 255, 255));
        input_contact.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        input_contact.setPhColor(new java.awt.Color(255, 255, 0));
        jPanel2.add(input_contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 520, 300, 30));

        input_password.setBackground(new java.awt.Color(108, 99, 255));
        input_password.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        input_password.setForeground(new java.awt.Color(100, 240, 240));
        input_password.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        input_password.setText("1234");
        input_password.setCaretColor(new java.awt.Color(255, 255, 255));
        input_password.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        input_password.setPhColor(new java.awt.Color(255, 255, 0));
        input_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_passwordActionPerformed(evt);
            }
        });
        jPanel2.add(input_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, 300, 30));

        input_staff_id.setBackground(new java.awt.Color(108, 99, 255));
        input_staff_id.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        input_staff_id.setForeground(new java.awt.Color(100, 240, 240));
        input_staff_id.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        input_staff_id.setText("1234");
        input_staff_id.setCaretColor(new java.awt.Color(255, 255, 255));
        input_staff_id.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        input_staff_id.setPhColor(new java.awt.Color(255, 255, 0));
        jPanel2.add(input_staff_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 300, 30));

        input_email.setBackground(new java.awt.Color(108, 99, 255));
        input_email.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        input_email.setForeground(new java.awt.Color(100, 240, 240));
        input_email.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        input_email.setText("sandajivincent@gmail.com");
        input_email.setCaretColor(new java.awt.Color(255, 255, 255));
        input_email.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        input_email.setPhColor(new java.awt.Color(255, 255, 0));
        jPanel2.add(input_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 300, 30));

        input_username.setBackground(new java.awt.Color(108, 99, 255));
        input_username.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        input_username.setForeground(new java.awt.Color(100, 240, 240));
        input_username.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        input_username.setText("ijamy");
        input_username.setCaretColor(new java.awt.Color(255, 255, 255));
        input_username.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        input_username.setPhColor(new java.awt.Color(255, 255, 0));
        input_username.setPlaceholder("please enter your name");
        input_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_usernameFocusLost(evt);
            }
        });
        jPanel2.add(input_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 300, 30));

        login_Btn.setBackground(new java.awt.Color(179, 147, 108));
        login_Btn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        login_Btn.setText("LOGIN");
        jPanel2.add(login_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 660, 190, 50));

        register_Btn.setBackground(new java.awt.Color(113, 31, 72));
        register_Btn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        register_Btn.setText("SIGN UP");
        register_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_BtnActionPerformed(evt);
            }
        });
        jPanel2.add(register_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 590, 190, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Secured_Letter_50px.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 50, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 50, 60));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Secure_50px.png"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 50, 60));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Google_Mobile_50px.png"))); // NOI18N
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, 50, 60));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 50, 60));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, 500, 740));

        setSize(new java.awt.Dimension(1132, 750));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void register_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_BtnActionPerformed

        if ( validateRegister() == true) {
            if (checkDublicateUsers() == false){
                insertRegisterDetails(); 
            } else{
                 JOptionPane.showMessageDialog(this,"user already exist");
            }
               
  }      
    }//GEN-LAST:event_register_BtnActionPerformed

    private void input_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_passwordActionPerformed

    private void input_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_usernameFocusLost
      if (checkDublicateUsers()== true){
          JOptionPane.showMessageDialog(this,"user already exist");
      }
    }//GEN-LAST:event_input_usernameFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Register().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel contact;
    private javax.swing.JLabel email;
    private app.bolivia.swing.JCTextField input_contact;
    private app.bolivia.swing.JCTextField input_email;
    private app.bolivia.swing.JCTextField input_password;
    private app.bolivia.swing.JCTextField input_staff_id;
    private app.bolivia.swing.JCTextField input_username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private necesario.RSMaterialButtonCircle login_Btn;
    private javax.swing.JLabel password;
    private necesario.RSMaterialButtonCircle register_Btn;
    private javax.swing.JLabel school_title;
    private javax.swing.JLabel staff_id;
    private javax.swing.JLabel title;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
